USE [bigdb]
GO
DROP TABLE IF EXISTS [bigtab]
GO
CREATE TABLE [bigtab] (col1 INT PRIMARY KEY CLUSTERED, col2 CHAR (7000) NOT NULL)
GO
SET NOCOUNT ON
GO
DECLARE @x INT
SET @x = 0
WHILE (@x < 100000)
BEGIN
    INSERT INTO [bigtab] VALUES (@x , 'x')
    SET @x = @x + 1
END
GO
SET NOCOUNT OFF
GO