CREATE EVENT SESSION [waits_and_latches] ON SERVER 
ADD EVENT sqlos.wait_info_external(
    ACTION(package0.callstack_rva)
    WHERE ([wait_type]='PREEMPTIVE_OS_WRITEFILEGATHER')),
ADD EVENT sqlserver.latch_suspend_end(
    ACTION(package0.callstack_rva)
    WHERE ([class]='FGCB_ADDREMOVE'))
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=30 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
GO


