USE GapFilling;
GO
SELECT timestamp
	   , VoltageReading
	   , FIRST_VALUE (VoltageReading) IGNORE NULLS OVER (
			ORDER BY timestamp ASC ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING 
			) AS [FIRST_VALUE]
		, LAST_VALUE (VoltageReading) IGNORE NULLS OVER (
			ORDER BY timestamp ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW 
			) AS [LAST_VALUE]
FROM MachineTelemetry
ORDER BY [timestamp];
GO