-- Turn off memory grant feedback
USE [WideWorldImportersDW]
GO
-- Step 2: Simulate statistics out of date
UPDATE STATISTICS Fact.OrderHistory 
WITH ROWCOUNT = 5000000000
GO
ALTER DATABASE SCOPED CONFIGURATION CLEAR PROCEDURE_CACHE
GO
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = OFF
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF
GO