USE master;
GO
ALTER DATABASE [AdventureWorks_EXT] SET COMPATIBILITY_LEVEL = 160;
GO
-- Clear the Query Store and set SQL Server 2019 defaults
--
ALTER DATABASE [AdventureWorks_EXT] SET QUERY_STORE CLEAR ALL;
GO
/* 
ALTER DATABASE [AdventureWorks_EXT]
SET QUERY_STORE = ON
    (
      OPERATION_MODE = READ_WRITE,
      CLEANUP_POLICY = ( STALE_QUERY_THRESHOLD_DAYS = 90 ),
      DATA_FLUSH_INTERVAL_SECONDS = 900,
      MAX_STORAGE_SIZE_MB = 1000,
      INTERVAL_LENGTH_MINUTES = 60,
      SIZE_BASED_CLEANUP_MODE = AUTO,
      MAX_PLANS_PER_QUERY = 200,
      WAIT_STATS_CAPTURE_MODE = ON,
      QUERY_CAPTURE_MODE = AUTO
);
*/
USE [AdventureWorksDW2016_EXT];
GO
ALTER DATABASE SCOPED CONFIGURATION CLEAR PROCEDURE_CACHE;
GO