USE MASTER;
GO
DROP DATABASE IF EXISTS guyinacubedb;
GO
CREATE DATABASE guyinacubedb;
GO
USE guyinacubedb;
GO
DROP TABLE IF EXISTS bigtab;
GO
CREATE TABLE bigtab (col1 INT PRIMARY KEY CLUSTERED, col2 CHAR(5000) NOT NULL);
GO
SET NOCOUNT ON;
GO
BEGIN TRAN;
GO
DECLARE @i INT;
SET @i = 0;
WHILE (@i < 1000000)
BEGIN
	INSERT INTO bigtab VALUES (@i, 'Who is the original Guy in a Cube?');
	SET @i = @i + 1;
END
GO
COMMIT TRAN;
GO
SET NOCOUNT OFF;
GO