CREATE USER orauser IDENTIFIED BY orapwd DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;
GRANT CREATE SESSION TO orauser;
GRANT CREATE TABLE TO orauser;
GRANT CREATE VIEW TO orauser;
GRANT CREATE ANY TRIGGER TO orauser;
GRANT CREATE ANY PROCEDURE TO orauser;
GRANT CREATE SEQUENCE TO orauser;
GRANT CREATE SYNONYM TO orauser;
