-- This is a similar query to Query 3 from the TPC-H benchmark
--
SELECT	TOP 10
	L_ORDERKEY,
	SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT))	AS REVENUE,
	O_ORDERDATE,
	O_SHIPPRIORITY,
	N.N_NAME
FROM	CUSTOMER C,
	ORDERS,
	LINEITEM,
	NATION N
WHERE	C_MKTSEGMENT	= 'BUILDING' AND
	C_CUSTKEY	= O_CUSTKEY AND
	L_ORDERKEY	= O_ORDERKEY AND
	O_ORDERDATE	< '1995-03-15' AND
	L_SHIPDATE	> '1995-03-15'
	AND C.C_NATIONKEY = N.N_NATIONKEY
GROUP	BY	L_ORDERKEY,
		O_ORDERDATE,
		O_SHIPPRIORITY,
		N.N_NAME
ORDER	BY	REVENUE DESC,
		O_ORDERDATE
