USE [WideWorldImporters]
GO
DROP SEQUENCE IF EXISTS [Sequences].[PersonID]
GO
CREATE SEQUENCE [Sequences].[PersonID] 
 AS [int]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 2147483647
 CACHE 
GO
DROP SEQUENCE IF EXISTS [Sequences].[CustomerID]
GO
CREATE SEQUENCE [Sequences].[CustomerID] 
 AS [int]
 START WITH 0
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 2147483647
 CACHE 
GO