USE MASTER
GO
IF EXISTS (SELECT * FROM sys.server_audit_specifications WHERE name = 'AuditSQLServerSpec')
BEGIN
    ALTER SERVER AUDIT SPECIFICATION AuditSQLServerSpec WITH (STATE = OFF)
    DROP SERVER AUDIT SPECIFICATION AuditSQLServerSpec
END
GO
CREATE SERVER AUDIT SPECIFICATION AuditSQLServerSpec
FOR SERVER AUDIT AuditSQLServer
    ADD (SUCCESSFUL_LOGIN_GROUP)
WITH (STATE = ON)
GO