CREATE AVAILABILITY GROUP [readscaleag]
    WITH (CLUSTER_TYPE = NONE)
    FOR REPLICA ON
        N'bwsql2017ws2016' 
	WITH (
	    ENDPOINT_URL = N'tcp://bwsql2017ws2016:5022',
	    AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
	    SEEDING_MODE = AUTOMATIC,
		FAILOVER_MODE = MANUAL,
		SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
		),
        N'bwsql2017rhel' 
	WITH (
	    ENDPOINT_URL = N'tcp://bwsql2017rhel:5022',
	    AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT,
	    SEEDING_MODE = AUTOMATIC,
		FAILOVER_MODE = MANUAL,
		SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
        )
go
