USE MASTER;
GO
ALTER DATABASE [showmethemoney] SET EMERGENCY;
GO
ALTER DATABASE [showmethemoney] SET SINGLE_USER;
GO
DBCC CHECKDB (N'showmethemoney', REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS, NO_INFOMSGS;
GO